### ISSUE TITLE
End chat

### ISSUE THREAD

**Issue by ToThangGTVT** [edmund5/anonymous-chat#1]
After endchat, another person can still connect to person who disconnected

**Comment by edmund5** [comment]
> 
> 
> After endchat, another person can still connect to person who disconnected

How many users you can currently have in database?

**Comment by ToThangGTVT** [comment]
I tested with 2 person in database. But now I have deployed your code again to 000webhost, and I executed query DELETE 2 person conneted together.
Finish, It worked properly.
Thank you for helping me create a bot ❤
